### ISSUE TITLE
Todo 11-25

### ISSUE THREAD

**Issue by frndhoon** [woo-woong/finpoint#8]
### 공통
- [ ] 직접 사용자 입장에서 시연해보면서 불편한 점 기록
### 상웅
- [ ] 사진 자료(erdcloud, 프롬프트, gpt 코드)
- [ ] README 상세 정리

### 정훈
- [ ] 영상 만들기
- [ ] PPT 아이디어
